spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #将注册到nacos上的服务ID转小写
          lower-case-service-id: true
      routes:
         #oauth授权服务器zbf-auth-core
         - id: zbf-auth-core
           uri: lb://zbf-auth-core
           predicates:
           - Path=/auth/**
           filters:
             #表示去掉api前缀
             - StripPrefix=1
             #- name: Hystrix
               #args:
                    #name: fallbackdd
                    #fallbackUri: 'forward:/fallback'
        #oauth授权服务器zbf-auth-core
         - id: zbf-user-server
           uri: lb://zbf-user-server
           predicates:
           - Path=/user/**
           filters:
             #表示去掉api前缀
             - StripPrefix=1
             #- name: Hystrix
               #args:
                   #name: fallbackdd
                   #fallbackUri: 'forward:/fallback'
         - id: zbf-menu-server
           uri: lb://zbf-menu-server
           predicates:
           - Path=/menu/**
           filters:
               #表示去掉api前缀
             - StripPrefix=1
             #- name: Hystrix
               #args:
                   #name: fallbackdd
                   #fallbackUri: 'forward:/fallback'
         - id: zbf-role-server
           uri: lb://zbf-role-server
           predicates:
           - Path=/role/**
           filters:
               #表示去掉api前缀
               - StripPrefix=1
                 #- name: Hystrix
                 #args:
               #name: fallbackdd
               #fallbackUri: 'forward:/fallback'
         - id: zbf-deupload-server
           uri: lb://zbf-deupload-server
           predicates:
           - Path=/deupload/**
           filters:
               #表示去掉api前缀
               - StripPrefix=1
               #- name: Hystrix
               #args:
               #name: fallbackdd
               #fallbackUri: 'forward:/fallback'  -
         - id: zbf-job-server
           uri: lb://zbf-job-server
           predicates:
           - Path=/job/**
           filters:
               #表示去掉api前缀
               - StripPrefix=1
               #- name: Hystrix
               #args:
               #name: fallbackdd
               #fallbackUri: 'forward:/fallback'
hystrix.command.fallbackdd.execution.isolation.thread.timeoutInMilliseconds: 50000

